services:
  postgres:
    container_name: database
    image: postgres
    restart: always
    env_file:
      - ./.env
    hostname: postgres_database
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    links:
      - "postgres:database"
    container_name: adminer
    image: adminer
    restart: always
    environment:
      host: localhost
    ports:
      - 8080:8080

  backend:
    links:
      - "postgres:database"

    container_name: backend-app
    restart: always
    build: ./backend
    env_file:
      - ./.env
    ports:
      - 15000:5000


volumes:
  db-data: