"""update foreign keys

Revision ID: 11e13776127b
Revises: 6468096d3927
Create Date: 2024-03-09 23:00:00.628949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e13776127b'
down_revision: Union[str, None] = '6468096d3927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('prices_microcategory_id_fkey', 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'categories', ['category_id'], ['id'])
    op.drop_column('prices', 'microcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('microcategory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key('prices_microcategory_id_fkey', 'prices', 'categories', ['microcategory_id'], ['id'])
    op.drop_column('prices', 'category_id')
    # ### end Alembic commands ###
